# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Evaldas Latoškinas
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my developer blog!
github_username:  lightingft

# Build settings
markdown: kramdown
# theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.16.3"
plugins:
  - jekyll-feed
  - jekyll-include-cache

# Homepage
paginate: 5 # amount of posts to show
paginate_path: /page:num/

# Author
author:
  name: "Evaldas Latoškinas"
  avatar: "/assets/images/avatar.png"
  bio: "Hobbyist programmer, first year CS&E student, sole member & founder of Enlighten Works"
  location: "Delft, Netherlands"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://lightingft.github.io/"
    - label: "Enlighten Works blog"
      icon: "fab fa-blogger"
      url: "http://enlightenworks.blogspot.com/"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/lightingft"
    - label: "Google Play"
      icon: "fab fa-google-play"
      url: "https://play.google.com/store/apps/developer?id=Enlighten+Works"

# Post settings
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
